### ISSUE TITLE
broken form

### ISSUE THREAD

**Issue by vivkay** [vivkay/dsn1676-assignment-5#1]
Hi @thomasjbradley,

I decided to try this assignment from scratch. I watched about an hour of Lynda tutorials and am re-watching your videos and it's still jibberish...so I'm trying my best.

Already it's broken. Uggh! Javascript hates me! I'm just trying to get the form to do the basic thing, but the console.log is not showing anything.

Here's the html:

```
    <form method="post" action="#">
        <div>
            <label for="action">To Do</label>
            <input class="action" id="action">
        </div>
        <button type="submit">Add</button>
    </form>

```

and the javascript

```
var $form = $('.form');
var $action = $('.action');
var $list = $('.list');

$form.on('submit', function () {
   e.preventDefault();

var actionValue = $action.val();
    console.log(actionValue);
});
```

I've triple checked this with the dino video and can't understand why my console.log showing up empty when I type into the text field and click the button? :(

Thanks!

**Comment by vivkay** [comment]
Tried doing this part but something's definitely broken somewhere since the console.log is empty and nothing is happening...

```
var $form = $('.form');
var $action = $('.action');
var $list = $('.list');

$form.on('submit', function () {
    e.preventDefault();

    var $actionH2 = $('<h2>').html($action.val())
    console.log($actionValue);

    $li.append($actionH2);
    $list.append($li);
});
```

**Comment by vivkay** [comment]
Noticed I was missing the e in my function, updated, but still broken:

```
$form.on('submit', function (e) {
    e.preventDefault();
    var $actionH2 = $('<h2>').html($action.val());
    $li.append($actionH2);
    $list.append($li);
});
```

**Comment by thomasjbradley** [comment]
In the code, on this line:
https://github.com/vivkay/dsn1676-assignment-5/blob/gh-pages/js/main.js#L1
We're using a CSS selector to get access to the form.

Looking at that CSS selector, in between the quotes, is that how to select the form in the CSS file? Would `.form` work to be able to style it?

**Comment by vivkay** [comment]
That fixed it thanks!

**Comment by vivkay** [comment]
I thought it fixed it, but my form actually isn't functional at all. I can't get it to append anything...

**Comment by vivkay** [comment]
I re-watched the video and triple-checked everything! Why won't it append? :(

```
var $form = $('.form');
var $action = $('.action');
var $list = $('.list');

$form.on('submit', function (e) {
    e.preventDefault();

    var $li = $('<li>');
    var $actionH2 = $('<h2>').html($action.val());

    $li.append($actionH2);
    $list.append($li);

});
```

**Comment by vivkay** [comment]
Here's the html:

```
    <form method="post" class="form" action="#">
        <div>
            <label for="action">To Do</label>
            <input class="action" id="action">
        </div>
        <button type="submit">Add</button>
    </form>

    <ul></ul>

```

**Comment by thomasjbradley** [comment]
Double check the selector for the list in the Javascript code. On this line:
https://github.com/vivkay/dsn1676-assignment-5/blob/gh-pages/js/main.js#L3

**Comment by vivkay** [comment]
BOOYEAH! 

Thanks!

**Comment by thomasjbradley** [comment]
The problem is definitely solved, but why not put the class right on the `ul`?
https://github.com/vivkay/dsn1676-assignment-5/blob/gh-pages/index.html#L21-L23

**Comment by vivkay** [comment]
Done and done! Thanks!
