### ISSUE TITLE
inline issues

### ISSUE THREAD

**Issue by vivkay** [vivkay/dsn1676-assignment-5#3]
Hi @thomasjbradley, 

Egad! I'm having some serious display-inline issues on my (delightfully coloured) form:

![screen shot 2015-03-01 at 4 54 20 pm](https://cloud.githubusercontent.com/assets/6340292/6433092/ae63f726-c033-11e4-9b57-626c463c33db.png)

Both the Add button and my checkboxes are problems (the checkboxes I asked about in another issue, so for this one I'm most concerned with the Add button!)

Thanks!

**Comment by thomasjbradley** [comment]
It appears that the `button` is outside the `div` that contains the `input`: they should probably be together in the same element.

**Comment by vivkay** [comment]
That fixed the top add button thanks!
