### ISSUE TITLE
wacky line-through not working

### ISSUE THREAD

**Issue by vivkay** [vivkay/dsn1676-assignment-5#4]
Hey @thomasjbradley, 

For some reason the colour change works, but the line-through won't work when I click on my li items:

CSS 

```
.js-strike {
    text-decoration: line-through;
    color: red;
}
```

:pineapple:

**Comment by vivkay** [comment]
![screen shot 2015-03-01 at 5 04 27 pm](https://cloud.githubusercontent.com/assets/6340292/6433148/0d7ab140-c035-11e4-945d-0c2c31781cb1.png)

**Comment by vivkay** [comment]
ouch...I'm going to change the colours. That hurts...like a PRICKLY PINEAPPLE to the eyeballs :pineapple:  :pineapple:   :pineapple:

**Comment by vivkay** [comment]
(Random aside note: The pineapples in github inspired me...to do THIS!)

![screen shot 2015-03-01 at 5 19 58 pm](https://cloud.githubusercontent.com/assets/6340292/6433224/4d85da1a-c037-11e4-9435-7819a20f6be6.png)

**Comment by thomasjbradley** [comment]
For the `line-through`: a few people have been running into this, and I know how to solve the problem, but I don't know why it's happening.

On the `h2`, remove `display: inline-block`.

**Comment by vivkay** [comment]
that worked!
